apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: test-k8s-app-frontend-RESOURCE_SUFFIX-cert
  namespace: RESOURCE_SUFFIX
spec:
  domains:
    - DOMAIN_NAME_PLACEHOLDER # 交給 deploy.yml 替換