apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-k8s-app-RESOURCE_SUFFIX-deployment
  labels:
    app: test-k8s-app-RESOURCE_SUFFIX
spec:
  replicas: 2 # 跑兩個副本，達成高可用性
  selector:
    matchLabels:
      app: test-k8s-app-RESOURCE_SUFFIX
  template:
    metadata:
      labels:
        app: test-k8s-app-RESOURCE_SUFFIX
    spec:
      containers:
      - name: test-k8s-app-container
        # 這裡填入你 Artifact Registry 裡的 Image 路徑
        image: asia-east1-docker.pkg.dev/test-k8s-app-492717/test-k8s-app-repo/my-app:v1
        ports:
        - containerPort: 3000 # 你的程式監聽的 Port
        resources:
          requests:
            cpu: "1"         # 啟動時預留 1 核心
            memory: "1Gi"    # 啟動時預留 1GB 內存
          limits:
            cpu: "1"         # 最高限制 1 核心
            memory: "1Gi"    # 最高限制 1GB 內存 (避免 OOM)
        startupProbe:
          httpGet:
            path: /healthz
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20