apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: test-k8s-app-frontend-RESOURCE_SUFFIX-ssl-redirect-config
  namespace: RESOURCE_SUFFIX
spec:
  redirectToHttps:
    enabled: true
