apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets-provider
spec:
  provider: gcp
  secretObjects: # 自動將 Secret Manager 的值同步成 K8s Secret
  - secretName: db-password-secret # 這就是生成的 K8s Secret 名稱
    type: Opaque
    data:
    - objectName: "YOUR_GCP_APP_NAME-RESOURCE_SUFFIX-db-password" # 必須對應下面 secrets 裡的名稱
      key: password # 這就是 K8s Secret 裡面的 Key 名稱
  parameters:
    secrets: |
      - resourceName: "projects/YOUR_PROJECT_ID/secrets/YOUR_GCP_APP_NAME-RESOURCE_SUFFIX-db-password/versions/latest"
        fileName: "db-password" # 雖然改用 Secret 物件，但 CSI 仍需這個參數來觸發同步