apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-k8s-app-frontend-RESOURCE_SUFFIX-secrets-provider
  namespace: RESOURCE_SUFFIX
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/YOUR_PROJECT_ID/secrets/YOUR_GCP_APP_NAME-RESOURCE_SUFFIX-db-password/versions/latest"
        fileName: "db-password.txt"