apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets-provider
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/YOUR_PROJECT_ID/secrets/YOUR_GCP_APP_NAME-RESOURCE_SUFFIX-db-password/versions/latest"
        fileName: "db-password.txt"

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets-provider
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/test-k8s-app-492717/secrets/test-k8s-app-prod-db-password/versions/latest"
        fileName: "db-password.txt"